### ISSUE TITLE
Choosing Warsaw server queues to EU East instead of Poland

### ISSUE THREAD

**Issue by Skajdrowski** [Jyben/csgo-mm-server-picker#10]
Like the title says

I checked 3 times in console with ,,status" command

server should be named Valve CS:GO Poland server, but instead I'm getting queued to Valve EU East CS:GO Server

**Comment by Jyben** [comment]
Hi, 

I can't reproduce your issue. When I select only Warsaw, I'm connected to "Poland server" : 

![warsaw](https://user-images.githubusercontent.com/6501381/78039645-a9c3ce00-736e-11ea-96eb-a1a44f76871a.png)
![Poland server](https://user-images.githubusercontent.com/6501381/78039652-acbebe80-736e-11ea-9e41-b909e711e9b9.png)

But what is exaclty "Valve EU East CS:GO Server" ? Maybe this server is a part of the Warsaw cluster... 

Can you send me the ping measurement from your console when you start looking for a game ? You can make the test with a casual game. 

And if you have not yet received the last update (v1.1.1) I advize you to install it before : https://github.com/Jyben/csgo-mm-server-picker/releases/latest

**Comment by Skajdrowski** [comment]
I'm using the latest version. Casual will always queue to Polish servers but MM doesn't always work. Also on EU East I'm getting a littlebit higher ping than on Poland Servers

**Comment by Skajdrowski** [comment]
and the ping on EU East is simillar to "Vienna"

**Comment by Jyben** [comment]
Unfortunately I can't do more than block Valve's relay addresses to try redirect you on the closest server, we don't have access to the end server IPs because Valve hides them. 
All the relay addresses are found here : 
https://github.com/SteamDatabase/SteamTracking/blob/master/Random/NetworkDatagramConfig.json

**Comment by Skajdrowski** [comment]
So it is related to my internet connection ? That sucks because I got a friend who lives in a village and has poor internet. The only way was playing on warsaw servers :(

**Comment by Skajdrowski** [comment]
btw thank you for making this software, it helps to prevent queueing with Russian fellows ;)
