### ISSUE TITLE
error js on win10 update 

### ISSUE THREAD

**Issue by smnmasoud** [Jyben/csgo-mm-server-picker#112]
i updated win10rpo then occurred this error on running csgo-mm-server-picker 1.2.1:

===============================
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  ts: 1685707628432,
  pid: 9252,
  level: 'error',
  msg: [
    'Error: Request failed with status code 404\n' +
      '    at createError (C:\\Users\\smnma\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n' +
      '    at settle (C:\\Users\\smnma\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n' +
      '    at IncomingMessage.handleStreamEnd (C:\\Users\\smnma\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\node_modules\\axios\\lib\\adapters\\http.js:269:11)\n' +
      '    at IncomingMessage.emit (events.js:327:22)\n' +
      '    at endReadableNT (_stream_readable.js:1220:12)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:84:21)'
  ]
})
    at process.emit (events.js:304:17)
    at C:\Users\smnma\AppData\Local\Programs\csgo-mm-server-picker\resources\app.asar\app\main-process\simple-node-logger\lib\Logger.js:46:25
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
==================================================

i updated msc++  & java runtime (JRE) but not work more

**Comment by mobebek** [comment]
It's not problem with updates.
Problem is that in app/services/servers.js 
"https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json"
is deleted from SD github.

Replace that with last known file
"https://raw.githubusercontent.com/SteamDatabase/SteamTracking/0ae12036fceb607d31a2cecb504f4ffa6f52d306/Random/NetworkDatagramConfig.json"
and recompile installer.

Hit me up and I will send you updated version.

New to github so I don't know howw to post it in forks...

**Comment by HAKKER147579** [comment]
Has anybody released a patch for the issue yet i have been trying to get it working for a while now but nothing is working

**Comment by RealMOH** [comment]
Same issue windows 11

**Comment by anatidaeta** [comment]
> It's not problem with updates. Problem is that in app/services/servers.js "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json" is deleted from SD github.
> 
> Replace that with last known file "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/0ae12036fceb607d31a2cecb504f4ffa6f52d306/Random/NetworkDatagramConfig.json" and recompile installer.
> 
> Hit me up and I will send you updated version.
> 
> New to github so I don't know howw to post it in forks...

what directory is it missing from? im not too knowledgeable about recompiling an installer

**Comment by mountaincastle47** [comment]
> It's not problem with updates. Problem is that in app/services/servers.js "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json" is deleted from SD github.
> 
> Replace that with last known file "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/0ae12036fceb607d31a2cecb504f4ffa6f52d306/Random/NetworkDatagramConfig.json" and recompile installer.
> 
> Hit me up and I will send you updated version.
> 
> New to github so I don't know howw to post it in forks...

hey man can you upload the installer to google drive, mega, anonfiles etc?

**Comment by FN-FAL113** [comment]
[CS GO Server Picker](https://github.com/FN-FAL113/csgo-server-picker)
Feel free to try it out! simple and lightweight, delete this comment if not allowed

**Comment by StudioAndromeda** [comment]
> It's not problem with updates. Problem is that in app/services/servers.js "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json" is deleted from SD github.
> 
> Replace that with last known file "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/0ae12036fceb607d31a2cecb504f4ffa6f52d306/Random/NetworkDatagramConfig.json" and recompile installer.
> 
> Hit me up and I will send you updated version.
> 
> New to github so I don't know howw to post it in forks...

I have made the change and recompile the installer, that works for me !
Also the Mega link to the fixed version for anyone that couldn't find a solution yet :
https://mega.nz/file/gH9nHBQS#3KzfyIIqhsIK_pvlw3ZT-qlnINsD6hMTs7yHBEDKm5o

**Comment by Chopper1337** [comment]
Check #113, it uses the latest versions of the JSON from Valve.

**Comment by mountaincastle47** [comment]
> > It's not problem with updates. Problem is that in app/services/servers.js "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json" is deleted from SD github.
> > Replace that with last known file "https://raw.githubusercontent.com/SteamDatabase/SteamTracking/0ae12036fceb607d31a2cecb504f4ffa6f52d306/Random/NetworkDatagramConfig.json" and recompile installer.
> > Hit me up and I will send you updated version.
> > New to github so I don't know howw to post it in forks...
> 
> I have made the change and recompile the installer, that works for me ! Also the Mega link to the fixed version for anyone that couldn't find a solution yet : https://mega.nz/file/gH9nHBQS#3KzfyIIqhsIK_pvlw3ZT-qlnINsD6hMTs7yHBEDKm5o

Thanks :DDDD 
(confirmed that the installer is clean myself)
