### ISSUE TITLE
resource issue

### ISSUE THREAD

**Issue by zygen22** [Jyben/csgo-mm-server-picker#115]
bro can you teach me fix this
![image](https://github.com/Jyben/csgo-mm-server-picker/assets/136184916/a8d86301-eddf-4c98-9b45-901019967696)

**Comment by zygen22** [comment]
@Jyben

**Comment by Betonung** [comment]
yeah i have this too

**Comment by Jyben** [comment]
It's fixed. You can open the application and the update will download automatically (you will receive a notification if you are on Windows). You will need to close the app for the update to install. If you do not receive the automatic update, you must first uninstall the application and then download the new release from Github.
