### ISSUE TITLE
we need update for cs2 and new servers

### ISSUE THREAD

**Issue by specurial** [Jyben/csgo-mm-server-picker#122]

**Comment by Boymerk** [comment]
are they not the same servrrs

**Comment by zSmartie** [comment]
Doesn't seem to be the same servers, no. As the tool is not working.

**Comment by specurial** [comment]
i guess most of them are same but i know they need to update this because when i block all servers my game still join to some servers this app not included to block ( or when i blocked only high ping servers, some times even this app can ping them or i joined to those in game)

**Comment by zSmartie** [comment]
This is because of relays, the game will connect you to Stockholm server through Frankfurt server for example. It's the Steam Datagram service and it can't be disabled as far as I know unfortunately.

**Comment by FN-FAL113** [comment]
> i guess most of them are same but i know they need to update this because when i block all servers my game still join to some servers this app not included to block ( or when i blocked only high ping servers, some times even this app can ping them or i joined to those in game)

https://github.com/FN-FAL113/cs2-server-picker

feel free to try it out (windows only app).
