### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Auditormadness9** [Jyben/csgo-mm-server-picker#127]
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  ts: 1703960005036,
  pid: 21056,
  level: 'error',
  msg: [
    'Error: You must specify a host to ping!\n' +
      '    at new Ping (C:\\Users\\user\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\app\\main-process\\ping-lite.js:14:11)\n' +
      '    at C:\\Users\\user\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\app\\main-process\\ping.js:27:20\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at C:\\Users\\user\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\app\\main-process\\ping.js:26:13\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at PingWrapper.execute (C:\\Users\\user\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\app\\main-process\\ping.js:12:31)\n' +
      '    at C:\\Users\\user\\AppData\\Local\\Programs\\csgo-mm-server-picker\\resources\\app.asar\\app\\main-process\\firewall.js:110:10\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
  ]
})
    at process.emit (events.js:304:17)
    at C:\Users\user\AppData\Local\Programs\csgo-mm-server-picker\resources\app.asar\app\main-process\simple-node-logger\lib\Logger.js:46:25
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

[OK]

**Comment by autelast** [comment]
I have the same problem

**Comment by Jyben** [comment]
It should be OK now. You can either restart the application, click OK on the error message, and wait for the app to download the update (you will receive a Windows notification once it's ready) and then restart the app. Or, you can uninstall it properly and download the latest version: https://github.com/Jyben/csgo-mm-server-picker/releases/tag/v1.2.3
