### ISSUE TITLE
Program not working

### ISSUE THREAD

**Issue by n1mas1le** [Jyben/csgo-mm-server-picker#128]
[csgo-mm-server-picker.log](https://github.com/Jyben/csgo-mm-server-picker/files/13876148/csgo-mm-server-picker.log)

![111111](https://github.com/Jyben/csgo-mm-server-picker/assets/156109831/a6fbeb3f-61c1-48bf-8fce-bb47a778723d)

**Comment by sosoabig** [comment]
have same

**Comment by Jyben** [comment]
It should be OK now. You can either restart the application, click OK on the error message, and wait for the app to download the update (you will receive a Windows notification once it's ready) and then restart the app. Or, you can uninstall it properly and download the latest version: https://github.com/Jyben/csgo-mm-server-picker/releases/tag/v1.2.3
