### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by sosoabig** [Jyben/csgo-mm-server-picker#130]
![image](https://github.com/user-attachments/assets/d7891971-af3a-43b6-a982-224e077ceb0a)
i turned on a firewall but it give me this problem pls help

**Comment by sosoabig** [comment]
@Jyben

**Comment by Jyben** [comment]
It should be OK now. You can either restart the application, click OK on the error message, and wait for the app to download the update (you will receive a Windows notification once it's ready) and then restart the app. Or, you can uninstall it properly and download the latest version: https://github.com/Jyben/csgo-mm-server-picker/releases/tag/v1.2.3
