### ISSUE TITLE
0ms on valve servers

### ISSUE THREAD

**Issue by T1Swz1T** [Jyben/csgo-mm-server-picker#17]
https://user-images.githubusercontent.com/59527538/85105774-b50ef300-b213-11ea-90f0-698c8c972a1d.gif

**Comment by Jyben** [comment]
Can you send me the log fiel at C:\Users\\**username**\AppData\Local\Programs\csgo-mm-server-picker please ?

**Comment by T1Swz1T** [comment]
nothing writes in log file

**Comment by Jyben** [comment]
Are you able to reach some of these adresses : https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json
With a ping command ?

**Comment by Luislanda132** [comment]
Hey jyben  there is anyway that using the mm csgo pick server i end up with no wifi in my pc? Please bro help me out, after an error window popped out from the app, i dont have any internet access on my computer :( i was using it with no problems dude

**Comment by Jyben** [comment]
No, the application simply adds rules in your firewall called "cs go mm server picker", you can delete them but there is no relation between the two
