### ISSUE TITLE
It's been 4 hours.

### ISSUE THREAD

**Issue by oyunali123** [Jyben/csgo-mm-server-picker#18]
I uninstall and reinstall again because of the new update however it's been 4 hours and it still not finished what should i do

![Hata2](https://user-images.githubusercontent.com/67159734/85150641-743acc80-b25b-11ea-87ef-ae38192f4913.PNG)

is it because of the language? (Turkish)

**Comment by Jyben** [comment]
I don't think so. Clean your installation with [CCleaner ](https://www.ccleaner.com/fr-fr/ccleaner/download) and try again.

**Comment by oyunali123** [comment]
it worked thanks
