### ISSUE TITLE
EU west selected, but EU east and north in queue

### ISSUE THREAD

**Issue by E1k3** [Jyben/csgo-mm-server-picker#21]
As the title says, when EU servers (namely Amsterdam, Frankfurt, Paris, Luxembourg) are the only ones selected, I regularly get connected to EU east and north servers.

I can't tell if this may be related to valve's relay server selection. If EU west relay servers can connect me to EU east/north game servers then I guess there is no way around this.

**Comment by Adicek-jpg** [comment]
Same, RIP CSGO for me if I have to play with Russians every match as my TF probably got lowered by inactivity for a few months. But I honestly think this tool just sucks, as you can connect to US servers if all EU servers are blocked, but if only EU east servers are blocked that means some servers in east are either not in the blocking list or some East addresses are in EU West list. But if you look at the grammar of this dev, I don't think he is the person to be able to make this tool workable.

**Comment by E1k3** [comment]
@Adicek-jpg 
> If only I knew where to find complete IP ranges of all servers I would be able to block them myself without using this not working tool.
Valve are actively trying to prevent that tho. Which is understandable when you consider that everyone could DDOS their servers if they didn't.
The way it is now, you connect to a relay server which in turn is connected to the game server.
Since you can only see and block the relay server IPs, you can e.g. block all relay servers except EU west, but the EU west relay servers may still connect you to EU east game servers.

As long as Valve keeps the possibility of relay servers of one region connecting to game servers from another region, there will be no way to block game servers by region.
