### ISSUE TITLE
Build for marc

### ISSUE THREAD

**Issue by alphonse92** [Jyben/csgo-mm-server-picker#35]
As you know, CSGO is available on mac and electron can build for mac. Thanks a lot!

**Comment by Jyben** [comment]
I know but I haven't found an easy way to block IP addresses on Mac. The code would be placed here :

https://github.com/Jyben/csgo-mm-server-picker/blob/a0d238c1dac57bb3a0452de4f2e23fa1a7ccb407/app/main-process/firewall.js#L27
