### ISSUE TITLE
Add Argentina servers to the list

### ISSUE THREAD

**Issue by SomeonefromArg** [Jyben/csgo-mm-server-picker#42]
please

**Comment by Jyben** [comment]
I will add it soon

**Comment by sdepolp** [comment]
I've downloaded the Source Code and added Argentina servers, actually testing on my local machine from Santiago, Chile, using an Optic Fiber connection provided by Entel.

![image](https://user-images.githubusercontent.com/42580141/109714071-b9502600-7b80-11eb-8013-3476a90e1d00.png)
