### ISSUE TITLE
App seems to have bricked my Network driver after receiving this error message?

### ISSUE THREAD

**Issue by alicsr** [Jyben/csgo-mm-server-picker#44]
Hi, received this message after finishing a game this evening.

https://i.imgur.com/ZS8shLJ.jpg

My network driver in my Mobo seems to be bricked after receiving this, resetting network seems to have no resolve and now beginning trouble shooting.

I force quit the software with task manager and am now unable to connect with this message when trouble shooting the issue https://i.imgur.com/ta7zISk.jpg

If you could tell me how this issue can be resolved, will be eternally grateful :) 

[log.log](https://github.com/Jyben/csgo-mm-server-picker/files/5993014/log.log)

**Comment by AguacateContreras** [comment]
Hello @alicsr 
As a user, what I do when I get that error is to hold space bar, like for half a minute until the javascript errors stop.
About the no internet issue you can try go to "Windows Defender Firewall >Advance settings >outbound rules" and look for "csgo-mm-server-picker"  (or something related), select those rules and delet them 

Hope that help you!
