### ISSUE TITLE
Add india west server

### ISSUE THREAD

**Issue by abdoxch** [Jyben/csgo-mm-server-picker#45]
when i use the app i only select to connect to dubai server 
but since the app doesnt block india west server 
i will sometimes get connected to india west server 
pls add it so i can block it

**Comment by sdepolp** [comment]
Hi, please confirm if you are trying to select Chennai or Mumbai, because CSGO has official servers hosted on that cities.

**Comment by abdoxch** [comment]
I'm not trying to select Chennai or Mumbai,
I'm trying to queue to Dubai only but I get connected to India west server and east,
which is Mumbai and Chennai I think,
I have updated to 1.1.4 version and I'm gonna see if it still happens.

**Comment by abdoxch** [comment]
I still get connected to India West Server and East,
I guess I'll wait for an update to add the servers.
