### ISSUE TITLE
[Error] Cannot find the file specified

### ISSUE THREAD

**Issue by Motias-git** [Jyben/csgo-mm-server-picker#49]
Issue: Selecting region, server, clicking GO and have this error
![image](https://user-images.githubusercontent.com/47714084/109953377-08b56400-7cf1-11eb-9389-2d8e2b9187cf.png)
Version: Windows build 1.1.4
LOG: `14:00:11.262 ERROR stderr: The system cannot find the file specified.`

**Comment by MotiasF33** [comment]
LOG:
`14:00:11.262 ERROR stderr: The system cannot find the file specified.`
may be i can run with debug?

**Comment by arggrande** [comment]
I believe this is fixed in 1.1.5 with #56 , verified this currently works correctly on Windows.

**Comment by MotiasF33** [comment]
> 
> 
> I believe this is fixed in 1.1.5 with #56 , verified this currently works correctly on Windows.

i test it
