### ISSUE TITLE
Java Error l

### ISSUE THREAD

**Issue by sarthakmalla** [Jyben/csgo-mm-server-picker#55]
Log
00:14:15.654 ERROR TypeError: Cannot read property 'concat' of undefined
    at Converter.convert (C:\Users\Sarthak Malla\AppData\Local\Programs\csgo-mm-server-picker\resources\app.asar\app\models\clusters.js:66:91)
    at Clusters.convert (C:\Users\Sarthak Malla\AppData\Local\Programs\csgo-mm-server-picker\resources\app.asar\app\models\clusters.js:98:25)
    at C:\Users\Sarthak Malla\AppData\Local\Programs\csgo-mm-server-picker\resources\app.asar\main.js:65:14
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by mountaincastle47** [comment]
i am having this too

**Comment by delcsgo** [comment]
same since yesterday

**Comment by amjoode21** [comment]
+3

**Comment by lauw0129** [comment]
+4

**Comment by Pidizl** [comment]
+5
![a69b1121489bf9b6673a23bb75f572d7](https://user-images.githubusercontent.com/63932196/115893723-d276a400-a458-11eb-90e0-daecf73032ea.jpg)

**Comment by vikrant699** [comment]
https://github.com/Jyben/csgo-mm-server-picker/pull/56

Opened a PR, should fix.

**Comment by jaydevgajjar21** [comment]
same error! what to do ? i'm stuck on EU server and can't reset. :/ please help

**Comment by khuzaimaBashir** [comment]
+1 , same error
[csgo-mm-server-picker.log](https://github.com/Jyben/csgo-mm-server-picker/files/6367923/csgo-mm-server-picker.log)

**Comment by sarthakmalla** [comment]
> #56
> 
> Opened a PR, should fix.

Can You Upload a working exe
As it’s open source

**Comment by sarthakmalla** [comment]
With The PR of vikrant699 i made a new build.Its working properly and thanks to vikrant699
https://github.com/sarthakmalla/csgo-mm-server-picker/releases/tag/1.1.5

**Comment by jaydevgajjar21** [comment]
> With The PR of vikrant699 i made a new build.Its working properly and thanks to vikrant699
> https://github.com/sarthakmalla/csgo-mm-server-picker/releases/tag/1.1.5

works! thank you so much :)
