### ISSUE TITLE
No Indian or SEA servers?

### ISSUE THREAD

**Issue by chilltyme** [Jyben/csgo-mm-server-picker#7]
There are none of the at least 4 servers in India and none of the Singapore servers. Only one "Asia" server which is in China seems like. Also no Japan servers. 

I also think Middle East has servers separately in UAE which are also not there. 

Please fix.

**Comment by chilltyme** [comment]
God why am I so stupid.....

**Comment by ankushsethi** [comment]
Well.. I was here for the same stupid reason lmao.. @Jyben May i suggest you to create some high level documentation for this.
