### ISSUE TITLE
The program does not properly receive PING command results on Windows

### ISSUE THREAD

**Issue by ic23** [Jyben/csgo-mm-server-picker#73]
On Windows 10 with a language other than English, the spelling of milliseconds on the command line may change.
For example: ms (eng) -> мс (rus)
This is why some people can't see the ping result of the Valve server
![image](https://user-images.githubusercontent.com/21969222/147892958-56815f4e-3301-4ca5-88bb-68d1009b0a01.png)

**Comment by ic23** [comment]
A temporary fix:
Install 7-Zip, install the asar plugin on it, unzip the asar file and change the text in one file to your own.
The file in which we change: \app\main-process\ping-lite.js

Before:
![image](https://user-images.githubusercontent.com/21969222/147892471-bb0b9204-43e1-47c9-bad5-133e3c64c49c.png)

After:
![image](https://user-images.githubusercontent.com/21969222/147892479-8a2a0899-a6cf-4fcf-881b-5ba2e5dc81b2.png)

**Comment by ic23** [comment]
Temporary fix: https://drive.google.com/file/d/1rM55pO-5o9gpfqprSJ2NXshW1286G_ni/view?usp=sharing

**Comment by ic23** [comment]
Temporary fix: https://drive.google.com/file/d/1caFKuKmac0U0jfycqhrChQCtxTZXze4Y/view?usp=sharing

**Comment by Jyben** [comment]
In the next update I will include your commit.
