### ISSUE TITLE
don't use this app, it completely breaks network driver

### ISSUE THREAD

**Issue by Mlek00** [Jyben/csgo-mm-server-picker#78]

**Comment by jonathanhns** [comment]
> No description provided.

How do I fix my network driver

**Comment by Jyben** [comment]
Unfortunately I can't get this bug. There is no "tricky" code in the app, so I don't know what the source of this bug and why it only appears only for a few users.

The only code that changes your configuration is in this [class](https://github.com/Jyben/csgo-mm-server-picker/blob/master/app/main-process/firewall.js).

And more specifically this line : https://github.com/Jyben/csgo-mm-server-picker/blob/1ba6216cd84b60bbf9b8969b81cc3ccabf49ed63/app/main-process/firewall.js#L20

You have more information about this command [here](https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/netsh-advfirewall-firewall-control-firewall-behavior).

If you have any issues, you can follow these steps to delete the rule that the app created :

- Shortcut Win + R
- Type wf.msc then press enter
- Go to Outbound rules
- Find rule named "csgo-mm-server-picker"
- Right click on it then select Delete 

If anyone else have this issue, please let me know by posting a new comment here with any informations than can be revelant. If you have an another issue not related to this one, please open an new issue.
