### ISSUE TITLE
Santiago Servers cannot be blocked

### ISSUE THREAD

**Issue by berrutti** [Jyben/csgo-mm-server-picker#8]
I saw in the code that the SCL (Santiago) servers are taken into consideration but there's currently no way to block them. 
I saw that you have a const with the clusters:
`const clusters = ['eu-west', 'eu-east', 'na-west', 'na-east', 'sa', 'oc', 'af', 'as'];`
I understand that these are little sets of ips, but if you select 'sa', Chile is not in the list of IPs to select, so currently there's no way to block those servers. 
I just tested it, blocked every server but Sao Paolo's and when I connected to a match, it was hosted on a Chilean server.
If you have a lot of work I can take a look and create a PR but I'm not familiar with the code so it would take a while.
Thanks

**Comment by berrutti** [comment]
I did a little more debugging. I found this piece of code:

```
      hosts.forEach(host => {
        var ping = new Ping(host);

        ping.send((err, time) => {

          if (err === null && time !== null) {
            this._updateClusterStatus(host, time, true);
          }
          else {
            this._updateClusterStatus(host, 0, false);
          }
        });

        setTimeout(function () {
          ping.stop();
        }, 30000);
      });
```
Which works fine by the way. The problem is that it relies on the ping to the relays which can sometimes fail.
For instance, I can ping the SCL Chile server from the console with:
ping 155.133.249.178
And it fails for me, but the relay server is still up. Maybe they block some connections or ips? Anyway, because of that ping dies, the isAlive flag is set to false (which is not technically true), and the server is not listed on the map.
Maybe you can add a checkbox to display "dead" relay servers and block them anyway?

Thanks a lot

**Comment by berrutti** [comment]
I did a little bit more debugging :P
I pinged every IP here:
https://raw.githubusercontent.com/SteamDatabase/SteamTracking/master/Random/NetworkDatagramConfig.json

...and found that these servers are timing out for me:

scl:
155.133.249.194 
155.133.249.178
155.133.249.162

canm:
183.232.225.21

sham:
117.184.42.132
117.184.42.134

waw:
155.133.230.66

I'm not sure if this will be the same for everyone, but at least for people in my IP range, these IPs are getting "lost" on the app and cannot be blocked.
Thanks a lot!

**Comment by Jyben** [comment]
Hi,

You mean you can't ping the SCL IP but you can reach these servers on CSGO ?

**Comment by berrutti** [comment]
Correct!
Take a look at the following screenshot which I just took:
![20200327084816_1](https://user-images.githubusercontent.com/13040974/77754373-012e0b00-700a-11ea-8ec6-663b079a5e57.jpg)
As you can see, I'm on a CS:GO Chile Server, even though my pings are still getting timed out:
![pings](https://user-images.githubusercontent.com/13040974/77754573-579b4980-700a-11ea-8ab7-ef49339447cb.JPG)

**Comment by Jyben** [comment]
I removed a control. Now the servers that can't be reachable will be added to the list and in the firewall. But don't forget that the servers that you select on the list are the servers you will be connected. So, if you select "Santiago" you will be connected on this server. 
I will publish the new release (v1.1.0) in few minutes.
