### ISSUE TITLE
Stopped working a while ago, cannot get into EU servers

### ISSUE THREAD

**Issue by HandsomeHarry** [Jyben/csgo-mm-server-picker#80]
I am physically located in NA, but every time I try to play in EU servers I still get matched in NA servers but with a high ping. Resetting in the app and reconnecting to the game lowers the ping to a normal value but I still can't connect to EU servers. Has something changed in CSGO servers?

**Comment by MrBoringCom** [comment]
I don't know, this used to work back in 2021, and it stopped working. So I switched to Valve Region selecter, and it worked. Right now it is broken due to steam update. I contacted the dev and he says he'll look into it.
