### ISSUE TITLE
Not able to install the latest release

### ISSUE THREAD

**Issue by berrutti** [Jyben/csgo-mm-server-picker#9]
I've downloaded the 1.1.0 version and the installer gets stuck halfway. I'm not sure if its a problem with my machine or what's going on but it's not working. I'll test it on another machine whenever I get the chance. Thanks

**Comment by Jyben** [comment]
Have you downloaded the executable from the web or did you get it from an automatic update ? I advize you to update the app with the auto updater (juste launch the app, wait for the notification then restart)

**Comment by berrutti** [comment]
I've deleted the app. That's why I installed it from the latest release .exe. I'm trying with an old release to see if I can get it to auto update

**Comment by Jyben** [comment]
OK let me know. In the last release I have upgraded the version of electron from v5 to v8 so it can be the cause.

**Comment by berrutti** [comment]
Sorry that I took so long to answer. I was able to install an old release, but the update prompt never appeared. I tried again with the latest version .exe but had no luck.
Thanks a lot for your help.
I want to make a video of this tool, I have a small youtube channel, and my viewers are mostly from Argentina. A lot of us used to block servers in the past (for instance, people who don't understand Portuguese and want to play in Lima, or people who want to play in BR but don't want to play in Chile, etc.), and after the SDR change we were not able to. This tool is precisely what we need, so thanks again for your efforts!

**Comment by Jyben** [comment]
Can you tell someone to try to install the last release ? If everyone have this problem I will downgrade the version of Electron.

**Comment by berrutti** [comment]
I got my brother in law to install the software and he was able to do it, so it must be a problem on my machine. You can close this issue. He also said that SCL servers are on the list with 0 ping so I guess it's working just fine.
Thanks a lot!

**Comment by Jyben** [comment]
How did you remove the app at the first time ? Did you use the uninstaller executable : ![uninstaller](https://user-images.githubusercontent.com/6501381/77851058-f5dc0a80-71d6-11ea-9dde-9b4335b28838.PNG) 

I found this issue : https://github.com/electron-userland/electron-builder/issues/4057
So if you have deleted the app instead of uninstalling it you should use CCleaner as the last comment mentions

**Comment by berrutti** [comment]
Yeah I just removed the folder. I'll try with CCleaner. Thanks a lot!
