### ISSUE TITLE
How can I turn on my firewall?

### ISSUE THREAD

**Issue by AguacateContreras** [Jyben/csgo-mm-server-picker#90]
Hello, I'm getting the firewall warning but I already have it turned on and I don't know what should I do :(

![image](https://user-images.githubusercontent.com/52178199/174496899-8e20ac80-6c7a-4b44-bce9-190be797ffd7.png)

Any other consideration or tips?

Thank you!

**Comment by Jyben** [comment]
Hi, sorry it's my bad, I recently added this message and I shouldn't put it with a red color because it's just a reminder to inform the user that he needs to turn on windows firewall if it's not the case. Your conf is fine.
I will update this message.

Thank you for your report

**Comment by AguacateContreras** [comment]
Thank you @Jyben ! 🙌
